import kyu_6.Are_they_the_same.AreTheyTheSame;
import kyu_6.Bit_counting.BitCounting;
import kyu_6.Data_reverse.DataReverse;
import kyu_6.Detect_Pangram.DetectPangram;
import kyu_6.How_many_pages_in_a_book.HowManyPagesInABook;
import kyu_6.Is_a_number_prime.IsANumberPrime;
import kyu_6.Make_the_Deadfish_Swim.MakeTheDeadfishSwim;
import kyu_6.Missing_Alphabet.MissingAlphabet;
import kyu_6.More_Zeros_Than_Ones.MoreZerosThanOnes;
import kyu_6.Multiples_of_3_or_5.MultiplesOf3Or5;
import kyu_6.String_array_duplicates.StringArrayDuplicates;
import kyu_6.Sum_consecutives.SumConsecutives;
import kyu_6.Valid_Phone_Number.ValidPhoneNumber;
import kyu_6.Your_order_please.YourOrderPlease;
import kyu_7.Alphabet_war.AlphabetWar;
import kyu_7.Alphabetical_Addition.AlphabeticalAddition;
import kyu_7.Alternate_capitalization.AlternateCapitalization;
import kyu_7.Averages_of_Numbers.AveragesOfNumbers;
import kyu_7.Bit_manipulation.BitManipulation;
import kyu_7.Calculate_mean_and_concatenate_string.CalculateMeanAndConcatenateString;
import kyu_7.Character_counter.CharacterCounter;
import kyu_7.Check_three_and_two.CheckThreeAndTwo;
import kyu_7.Closest_to_Zero.ClosestToZero;
import kyu_7.Count_the_Digit.CountTheDigit;
import kyu_7.Count_the_divisors_of_a_number.CountTheDivisorsOfANumber;
import kyu_7.Credit_card_mask.CreditCardMask;
import kyu_7.Digitize.DigitizeKata;
import kyu_7.Dont_give_me_five.DontGiveMeFive;
import kyu_7.Fibonacci_Kata.Fibonacci;
import kyu_7.Find_Count_of_Most_Frequent_Item_in_an_Array.FindCountOfMostFrequentItemInAnArray;
import kyu_7.From_A_to_Z.FromAtoZ;
import kyu_7.Inspiring_Strings.InspiringStrings;
import kyu_7.Lost_number_in_number_sequence.LostNumberInNumberSequence;
import kyu_7.Maximum_Product.MaximumProduct;
import kyu_7.Move_10.Move10;
import kyu_7.Numbers_with_this_digit_inside.NumbersWithThisDigitInside;
import kyu_7.Password_maker.PasswordMaker;
import kyu_7.Plus_minus_Count.PlusMinusCount;
import kyu_7.RemoveDuplicateWords.RemoveDuplicateWords;
import kyu_7.Reverse_a_number.ReverseANumber;
import kyu_7.Reverse_letter.ReverseLetter;
import kyu_7.Round_up_to_the_next_multiple_of_5.RoundUpToTheNextMultipleOf5;
import kyu_7.Shorter_concat_reverse_longer.ShorterConcatReverseLonger;
import kyu_7.Simple_consecutive_pairs.SimpleConsecutivePairs;
import kyu_7.Simple_equation_reversal.SimpleEquationReversal;
import kyu_7.Smallest_value_of_an_array.SmallestValueOfAnArray;
import kyu_7.Split_In_Parts.SplitInParts;
import kyu_7.String_prefix_and_suffix.StringPrefixAndSuffix;
import kyu_7.Sum_of_odd_numbers.SumOfOddNumbers;
import kyu_7.Vaporcode_Kata.Vaporcode;
import kyu_7.Word_values.WordValues;
import kyu_8.Convert_number_to_reversed_array_of_digits.ConvertNumberToReversedArrayOfDigits;
import kyu_8.Merging_sorted_integer_arrays.MergingSortedIntegerArrays;
import kyu_8.Sum_of_Multiples.SumOfMultiples;
import kyu_8.Sum_without_highest_and_lowest_number.SumWithoutHighestAndLowestNumber;

import java.util.Arrays;
import java.util.List;

public class Main {
    public static void main(String[] args) {

//        System.out.println(YourOrderPlease.order("is2 Thi1s T4est 3a"));
//        System.out.println(MissingAlphabet.insertMissingLetters("hello"));
//        String[] test = StringArrayDuplicates.dup(new String[] {"kelless","keenness"});
//        System.out.println(ReverseLetter.reverseLetter("krish21an"));
//        System.out.println(CharacterCounter.validateWord("abc123"));
//        System.out.println(AlternateCapitalization.capitalize("abcdef"));
//        System.out.println(RoundUpToTheNextMultipleOf5.roundToNext5(0));
//        DataReverse.dataReverse(new int[]{1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,1,0,1,0,1,0});
//        System.out.println(CreditCardMask.maskify(""));
//        System.out.println(RemoveDuplicateWords.removeDuplicateWords("alpha beta beta gamma gamma gamma delta alpha beta beta gamma gamma gamma delta"));
//        System.out.println(DontGiveMeFive.dontGiveMeFive(-39,28));
//        System.out.println(AlphabetWar.alphabetWar("z"));
//        System.out.println(MultiplesOf3Or5.solution(10));
//        System.out.println(BitCounting.countBits(1234));
//        System.out.println(IsANumberPrime.isPrime(34));
//        System.out.println(AreTheyTheSame.comp(new int[]{2,2,3}, new int[]{4,9,9}));
//        System.out.println(MakeTheDeadfishSwim.parse("iiisdoso"));
//        System.out.println(ValidPhoneNumber.validPhoneNumber("(1111)555 2345"));
//        System.out.println(AveragesOfNumbers.averages(new int[] { 2, -2, 2, -2, 2 }));
//        System.out.println(ReverseANumber.reverse( -123));
//        System.out.println(Move10.moveTen("testcase"));
//        System.out.println(MaximumProduct.adjacentElementsProduct(new int[] {1, 2, 3}));
//        System.out.println(DigitizeKata.digitize(0));
//        System.out.println(SumWithoutHighestAndLowestNumber.sum(new int[] { 6, 2, 1, 8, 10}));
//        System.out.println(ConvertNumberToReversedArrayOfDigits.digitize(35231));
//        System.out.println(MergingSortedIntegerArrays.mergeArrays(new int[] { 1, 3, 5 }, new int[] { 2, 4, 6 }));
//        System.out.println(DetectPangram.check("The quick brown fox jus over the lazy dog."));
//        System.out.println(PlusMinusCount.signChange(new int[] {}));
//        System.out.println(BitManipulation.eliminateUnsetBits("111"));
//        System.out.println(FromAtoZ.gimmeTheLetters("Q-Z"));
//        System.out.println(AlphabeticalAddition.addLetters("a", "b", "c"));
//        System.out.println(Fibonacci.fib(5));
//        System.out.println(SplitInParts.splitInParts("HelloKata", 1));
//        System.out.println(MoreZerosThanOnes.moreZeros("thequickbrownfoxjumpsoverthelazydog"));
//        System.out.println(NumbersWithThisDigitInside.numbersWithDigitInside(0, 0));
//        System.out.println(WordValues.nameValue(new String[]{"abcdefghijklmnopqrstuvwxyz","stamford bridge","haskellers"}));
//        System.out.println(InspiringStrings.longestWord("red blue gold"));
//        System.out.println(LostNumberInNumberSequence.findDeletedNumber(new int[]{1,2,3,4,5,6,7,8,9}, new int[]{5,7,6,9,4,8,1,2,3}));
//        System.out.println(HowManyPagesInABook.amountOfPages(5));
//        System.out.println(Vaporcode.vaporcode("Lets go to the movies"));
//        System.out.println(PasswordMaker.makePassword(""));
//        System.out.println(SmallestValueOfAnArray.findSmallest( new int [] {7, 12, 3, 2, 27} , "index"));
//        System.out.println(FindCountOfMostFrequentItemInAnArray.mostFrequentItemCount(new int[] {3, -1, -1}));
//        System.out.println(SimpleConsecutivePairs.solve(new int[]{1,2,5,8,-4,-3,7,6,5}));
//        System.out.println(ClosestToZero.find(new int[] { 10, 3, 9, 1 }));
//        System.out.println(ClosestToZero.find(new int[] { 2, 4, -1, -3 }));
//        System.out.println(ClosestToZero.find(new int[] { 13, 0, -6 }));
//        System.out.println(ClosestToZero.find(new int[] { 5, 2, 2 }));
//        System.out.println(CountTheDigit.nbDig(11549, 1));
//        System.out.println(StringPrefixAndSuffix.solve("aaaa"));
//        System.out.println(SimpleEquationReversal.solve("100*b/y"));
//        System.out.println(SimpleEquationReversal.solve("a+b-c/d*30"));
//        System.out.println(CheckThreeAndTwo.checkThreeAndTwo(new char[] { 'a', 'a', 'a', 'a', 'a' }));
//        System.out.println(SumOfOddNumbers.rowSumOddNumbers(1));
//        System.out.println(CalculateMeanAndConcatenateString.mean(new char[] {'0', 'u', 'a', 'y', '0', 'a', '9', 'q', '3', 'v', 'g', '7', '6', '4', 'y', 'd', '8', '6', '0', 'd'}));
//        System.out.println(CountTheDivisorsOfANumber.numberOfDivisors(30));
//        System.out.println(ShorterConcatReverseLonger.shorterReverseLonger("hello", "bau"));
//        System.out.println(SumOfMultiples.sumMul(4, 123));
        System.out.println(SumConsecutives.sumConsecutives(Arrays.asList(1,4,4,4,0,4,3,3,1)));
    }
}
