import kyu_6.Are_they_the_same.AreTheyTheSame;
import kyu_6.Bit_counting.BitCounting;
import kyu_6.Data_reverse.DataReverse;
import kyu_6.Detect_Pangram.DetectPangram;
import kyu_6.Fruit_Machine.FruitMachine;
import kyu_6.Is_a_number_prime.IsANumberPrime;
import kyu_6.Make_the_Deadfish_Swim.MakeTheDeadfishSwim;
import kyu_6.Missing_Alphabet.MissingAlphabet;
import kyu_6.More_Zeros_Than_Ones.MoreZerosThanOnes;
import kyu_6.Multiples_of_3_or_5.MultiplesOf3Or5;
import kyu_6.String_array_duplicates.StringArrayDuplicates;
import kyu_6.Valid_Phone_Number.ValidPhoneNumber;
import kyu_6.Your_order_please.YourOrderPlease;
import kyu_7.Alphabet_war.AlphabetWar;
import kyu_7.Alphabetical_Addition.AlphabeticalAddition;
import kyu_7.Alternate_capitalization.AlternateCapitalization;
import kyu_7.Averages_of_Numbers.AveragesOfNumbers;
import kyu_7.Bit_manipulation.BitManipulation;
import kyu_7.Character_counter.CharacterCounter;
import kyu_7.Credit_card_mask.CreditCardMask;
import kyu_7.Digitize.DigitizeKata;
import kyu_7.Dont_give_me_five.DontGiveMeFive;
import kyu_7.Fibonacci_Kata.Fibonacci;
import kyu_7.From_A_to_Z.FromAtoZ;
import kyu_7.Maximum_Product.MaximumProduct;
import kyu_7.Move_10.Move10;
import kyu_7.Numbers_with_this_digit_inside.NumbersWithThisDigitInside;
import kyu_7.Plus_minus_Count.PlusMinusCount;
import kyu_7.RemoveDuplicateWords.RemoveDuplicateWords;
import kyu_7.Reverse_a_number.ReverseANumber;
import kyu_7.Reverse_letter.ReverseLetter;
import kyu_7.Round_up_to_the_next_multiple_of_5.RoundUpToTheNextMultipleOf5;
import kyu_7.Split_In_Parts.SplitInParts;
import kyu_8.Convert_number_to_reversed_array_of_digits.ConvertNumberToReversedArrayOfDigits;
import kyu_8.Merging_sorted_integer_arrays.MergingSortedIntegerArrays;
import kyu_8.Sum_without_highest_and_lowest_number.SumWithoutHighestAndLowestNumber;

import java.math.BigInteger;

public class Main {
    public static void main(String[] args) {

        //System.out.println(YourOrderPlease.order("is2 Thi1s T4est 3a"));
        //System.out.println(MissingAlphabet.insertMissingLetters("hello"));
        //String[] test = StringArrayDuplicates.dup(new String[] {"kelless","keenness"});
        //System.out.println(ReverseLetter.reverseLetter("krish21an"));
        //System.out.println(CharacterCounter.validateWord("abc123"));
        //System.out.println(AlternateCapitalization.capitalize("abcdef"));
        //System.out.println(RoundUpToTheNextMultipleOf5.roundToNext5(0));
        //DataReverse.dataReverse(new int[]{1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,1,0,1,0,1,0});
        //System.out.println(CreditCardMask.maskify(""));
        //System.out.println(RemoveDuplicateWords.removeDuplicateWords("alpha beta beta gamma gamma gamma delta alpha beta beta gamma gamma gamma delta"));
        //System.out.println(DontGiveMeFive.dontGiveMeFive(-39,28));
        //System.out.println(AlphabetWar.alphabetWar("z"));
        //System.out.println(MultiplesOf3Or5.solution(10));
        //System.out.println(BitCounting.countBits(1234));
        //System.out.println(IsANumberPrime.isPrime(34));
        //System.out.println(AreTheyTheSame.comp(new int[]{2,2,3}, new int[]{4,9,9}));
        //System.out.println(MakeTheDeadfishSwim.parse("iiisdoso"));
        //System.out.println(ValidateCreditCardNumber.validate("1230"));
        //System.out.println(ValidateCreditCardNumber.validate("891"));
        //System.out.println(ValidateCreditCardNumber.validate("123"));
        //System.out.println(ValidPhoneNumber.validPhoneNumber("(1111)555 2345"));
        //System.out.println(AveragesOfNumbers.averages(new int[] { 2, -2, 2, -2, 2 }));
        //System.out.println(ReverseANumber.reverse( -123));
        //System.out.println(Move10.moveTen("testcase"));
        //System.out.println(MaximumProduct.adjacentElementsProduct(new int[] {1, 2, 3}));
        //System.out.println(DigitizeKata.digitize(0));
        //System.out.println(SumWithoutHighestAndLowestNumber.sum(new int[] { 6, 2, 1, 8, 10}));
        //System.out.println(ConvertNumberToReversedArrayOfDigits.digitize(35231));
        //System.out.println(MergingSortedIntegerArrays.mergeArrays(new int[] { 1, 3, 5 }, new int[] { 2, 4, 6 }));
        //System.out.println(DetectPangram.check("The quick brown fox jus over the lazy dog."));
        //System.out.println(PlusMinusCount.signChange(new int[] {}));
        //System.out.println(BitManipulation.eliminateUnsetBits("111"));
        //System.out.println(FromAtoZ.gimmeTheLetters("Q-Z"));
        //System.out.println(AlphabeticalAddition.addLetters("a", "b", "c"));
        //System.out.println(Fibonacci.fib(5));
        //System.out.println(SplitInParts.splitInParts("HelloKata", 1));
        //System.out.println(MoreZerosThanOnes.moreZeros("thequickbrownfoxjumpsoverthelazydog"));
        System.out.println(NumbersWithThisDigitInside.numbersWithDigitInside(0, 0));
    }
}
